version: '3'

services:
  tomcat:
    build:
      context: .
      dockerfile: ./web/dockerfile
    environment:
      BASE_API_URL: http://api:8081/
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      dockerfile: ./api/dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/consulta_cnpj_db
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consulta_cnpj_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: